// catalog-data.mjs — data katalog terkurasi (estimasi harga lokal, JPY untuk tokyo / KRW untuk seoul)
// Format base: { id, n: nama, d: deskripsi, c: kategori, s: toko, t: "tokyo"|"seoul", p: harga, [mk]: markup%, [f]: flat fee, [q]: query gambar, [vq]: 1 = tiap varian punya gambar sendiri, [v]: varian[] }
// Varian: string ATAU { n, [p], [q] }. id produk final: prod-<id>[-slug-varian]

export const BASES = [
  // ================= SNACKS =================
  { id: "kitkat-jp", n: "KitKat Japan Exclusive", d: "Japan-only KitKat flavors you simply cannot buy outside Japan.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 864, vq: 1, v: ["Strawberry Cheesecake", "Melon", "Sakura Mochi", "Hojicha", "Whole Grape", "Rum Raisin", "Sweet Potato", "Momiji Manju", "Amaou Strawberry", "Chocolate Orange"] },
  { id: "tokyobanana-var", n: "Tokyo Banana", d: "The iconic Tokyo Station omiyage, in its rarer flavors.", c: "Snacks", s: "Tokyo Station", t: "tokyo", p: 1250, vq: 1, v: ["Caramel", "Maple", "Honey", "Choco Banana Shake"] },
  { id: "pocky-premium", n: "Pocky Premium", d: "Grown-up Pocky lines rarely exported from Japan.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 540, vq: 1, v: ["Almond Crush", "Uji Matcha", "Amaou Strawberry", "Winter Melty", "Chocolat Orange"] },
  { id: "jagariko", n: "Calbee Jagariko Cup", d: "Crunchy potato sticks in a cup — konbini legend.", c: "Snacks", s: "FamilyMart", t: "tokyo", p: 180, vq: 1, v: ["Salad", "Cheese", "Butter Soy Sauce", "Mentaiko"] },
  { id: "jagabee", n: "Calbee Jagabee", d: "Skin-on potato fries snack, Japan-domestic recipe.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 320, vq: 1, v: ["Lightly Salted", "Butter Soy Sauce"] },
  { id: "countrymaam", n: "Country Ma'am Cookies", d: "Soft-baked cookies, bake them 30s for the full experience.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 398, vq: 1, v: ["Vanilla & Cocoa", "Matcha"] },
  { id: "hichew", n: "Hi-Chew Japan Flavors", d: "Japan-limited Hi-Chew flavors with real fruit juice.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 158, vq: 1, v: ["White Peach", "Muscat", "Yuzu"] },
  { id: "babystar", n: "Baby Star Ramen Snack", d: "Crispy noodle snack — childhood classic of Japan.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 240, vq: 1, v: ["Chicken", "Mentaiko"] },
  { id: "kakinotane", n: "Kameda Kaki no Tane", d: "Rice cracker & peanut mix, the ultimate beer buddy.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 380, vq: 1, v: ["Original", "Wasabi", "Umeboshi"] },
  { id: "yokumoku", n: "Yoku Moku Cigare", d: "Buttery rolled cookies — Japan's classy gift tin.", c: "Snacks", s: "Isetan Shinjuku", t: "tokyo", p: 1620, vq: 1, v: [{ n: "20 pcs" }, { n: "30 pcs", p: 2430 }] },
  { id: "pressbutter", n: "Press Butter Sand", d: "Butter caramel sandwich cookies with eternal Tokyo Station queues.", c: "Snacks", s: "Tokyo Station", t: "tokyo", p: 1404, vq: 1, v: ["Original 9pcs", "Uji Matcha 9pcs"] },
  { id: "nyperfectcheese", n: "N.Y. Perfect Cheese (12 pcs)", d: "The cheese langue de chat that sells out by noon.", c: "Snacks", s: "Tokyo Station", t: "tokyo", p: 1188 },
  { id: "sugarbutter", n: "Sugar Butter no Ki", d: "Toasted grain sandwich biscuits — Tokyo omiyage staple.", c: "Snacks", s: "Tokyo Station", t: "tokyo", p: 1080, vq: 1, v: [{ n: "14 pcs" }, { n: "24 pcs", p: 1830 }] },
  { id: "tokyorusk", n: "Tokyo Rusk Assortment", d: "Crispy rusk assortment in Japan-only flavors.", c: "Snacks", s: "Tokyo Station", t: "tokyo", p: 1080 },
  { id: "ningyoyaki", n: "Asakusa Ningyo-yaki (12 pcs)", d: "Hand-grilled castella dolls from Asakusa's oldest stalls.", c: "Snacks", s: "Asakusa Nakamise", t: "tokyo", p: 900 },
  { id: "hatosabure", n: "Hato Sabure (16 pcs)", d: "Kamakura's dove-shaped butter cookie, beloved for 120 years.", c: "Snacks", s: "Toshimaya Kamakura", t: "tokyo", p: 1512 },
  { id: "marusei", n: "Rokkatei Marusei Butter Sand (10 pcs)", d: "Hokkaido's legendary rum-raisin butter sandwich. Hand-carry only.", c: "Snacks", s: "Hokkaido Dosanko Plaza", t: "tokyo", p: 1500 },
  { id: "letao", n: "LeTAO Cheese Cookies", d: "Otaru's famous fromage cookies, airport favorite.", c: "Snacks", s: "Hokkaido Dosanko Plaza", t: "tokyo", p: 1296 },
  { id: "tirol", n: "Tirol Choco Party Box (27 pcs)", d: "Mini chocolates in absurdly fun Japan-only flavors.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 594 },
  { id: "meiji-choco", n: "Meiji Choco Snack", d: "The eternal kinoko-takenoko war, pick your side.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 230, vq: 1, v: ["Kinoko no Yama", "Takenoko no Sato"] },
  { id: "meltykiss", n: "Meiji Melty Kiss (Winter Only)", d: "Winter-limited melt-in-mouth chocolate cubes.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 298, vq: 1, v: ["Premium Chocolate", "Matcha"] },
  { id: "apollo", n: "Meiji Apollo Strawberry Choco", d: "Retro rocket-shaped strawberry chocolate since 1969.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 158 },
  { id: "dagashibox", n: "Dagashi Party Box (50 pcs)", d: "50 assorted retro penny snacks — instant nostalgia crate.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 1500 },
  { id: "weirdsnackbox", n: "Weird Japan Snack Box (Curated)", d: "We fill a box with the strangest snacks we find. Trust us.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 2000 },
  { id: "mentaisenbei", n: "Yamaya Mentaiko Senbei", d: "Spicy cod-roe crackers from Hakata, dangerously addictive.", c: "Snacks", s: "Hakata Miyage Ginza", t: "tokyo", p: 864 },
  { id: "royce-nama-var", n: "Royce' Nama Chocolate", d: "Hokkaido's silky ganache squares, more rare flavors.", c: "Snacks", s: "Royce' Shinjuku", t: "tokyo", p: 800, vq: 1, v: ["Matcha", "White", "Champagne"] },
  { id: "royce-potato", n: "Royce' Potatochip Chocolate", d: "Salty chips half-dipped in chocolate. Sounds wrong, tastes right.", c: "Snacks", s: "Royce' Shinjuku", t: "tokyo", p: 864, vq: 1, v: ["Original", "Mild Bitter"] },
  { id: "bake-cheese", n: "BAKE Creamy Cheese Tart (6 pcs)", d: "Freshly baked cheese tarts, Hokkaido-born cult hit.", c: "Snacks", s: "Lumine Shinjuku", t: "tokyo", p: 1560 },
  { id: "alfort", n: "Bourbon Alfort Premium", d: "Ship-embossed chocolate biscuits, premium Japan line.", c: "Snacks", s: "FamilyMart", t: "tokyo", p: 258, vq: 1, v: ["Milk", "Matcha"] },
  { id: "kanro-gummy", n: "Kanro Pure Gummy", d: "Heart-shaped sour-coated gummies, Japan-only flavors.", c: "Snacks", s: "FamilyMart", t: "tokyo", p: 190, vq: 1, v: ["Lemon", "Grape", "Yuzu"] },
  { id: "kororo", n: "UHA Kororo Gummy", d: "Bursting juice-sac gummies that feel like real fruit.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 214, vq: 1, v: ["Grape", "Muscat"] },
  { id: "fettuccine", n: "Bourbon Fettuccine Gummy", d: "Chewy flat sour gummies, konbini favorite.", c: "Snacks", s: "FamilyMart", t: "tokyo", p: 160 },
  { id: "sakuma", n: "Sakuma Drops Tin", d: "The nostalgic candy tin from 'Grave of the Fireflies'.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 450 },
  { id: "konpeito", n: "Kyoto Konpeito Jar", d: "Hand-crafted star sugar candy from a Kyoto atelier.", c: "Snacks", s: "Ryokujuan Shimizu Kyoto", t: "tokyo", p: 1080 },
  { id: "yatsuhashi", n: "Kyoto Nama Yatsuhashi", d: "Soft cinnamon mochi sheets folded over red bean — Kyoto only.", c: "Snacks", s: "Kyoto Station", t: "tokyo", p: 700, vq: 1, v: ["Cinnamon", "Matcha"] },
  { id: "cupnoodle-jp", n: "Nissin Cup Noodle (Japan Only)", d: "Japan-domestic Cup Noodle flavors, richer than export versions.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 236, vq: 1, v: ["Seafood", "Curry", "Chili Tomato"] },
  { id: "donbei", n: "Nissin Donbei Kitsune Udon (3 pk)", d: "The fluffy fried-tofu udon that airport shops can't keep stocked.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 645 },
  { id: "peyoung", n: "Peyoung Yakisoba GIGAMAX", d: "2,142 kcal of instant yakisoba. A challenge, not a meal.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 300 },
  { id: "popin-cookin", n: "Popin' Cookin' DIY Candy Kit", d: "Make-your-own candy chemistry sets — weirdly satisfying.", c: "Snacks", s: "Don Quijote Shinjuku", t: "tokyo", p: 320, vq: 1, v: ["Sushi Set", "Bento Set", "Donuts Set"] },
  { id: "honeybutter", n: "Honey Butter Almond", d: "Korea's airport-clearing almond snack.", c: "Snacks", s: "Emart Seoul", t: "seoul", p: 6980, vq: 1, v: ["Original", "Wasabi", "Injeolmi"] },
  { id: "turtlechips", n: "Orion Turtle Chips", d: "Quadruple-layered chips in Korea-only flavors.", c: "Snacks", s: "Emart Seoul", t: "seoul", p: 3480, vq: 1, v: ["Corn Soup", "Choco Churro"] },
  { id: "marketo", n: "Market O Real Brownie (8 pcs)", d: "Dense chocolate brownies, Korea's classic gift snack.", c: "Snacks", s: "Emart Seoul", t: "seoul", p: 5400 },
  { id: "butterwaffle", n: "Crown Butter Waffle", d: "Thin crispy butter waffles — Korean tea-time staple.", c: "Snacks", s: "Emart Seoul", t: "seoul", p: 3200 },
  { id: "pepero-premium", n: "Lotte Pepero Premium", d: "Korea's Pocky rival in premium editions.", c: "Snacks", s: "Emart Seoul", t: "seoul", p: 2800, vq: 1, v: ["Nude", "Almond"] },
  { id: "binch", n: "Lotte Binch Biscuits", d: "Half-chocolate half-biscuit elegance from Korea.", c: "Snacks", s: "Emart Seoul", t: "seoul", p: 3400 },

  // ================= BEVERAGES =================
  { id: "dassai-var", n: "Dassai Junmai Daiginjo", d: "Japan's most celebrated sake brewery, higher polish grades.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 2530, f: 70000, vq: 1, v: [{ n: "39 (720ml)" }, { n: "23 (720ml)", p: 5720 }] },
  { id: "kubota", n: "Kubota Senjyu Ginjo 720ml", d: "Clean, dry Niigata sake — izakaya gold standard.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 1540, f: 70000 },
  { id: "hakkaisan", n: "Hakkaisan Junmai Ginjo 720ml", d: "Snow-country sake, crisp and quietly perfect.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 1980, f: 70000 },
  { id: "kokuryu", n: "Kokuryu Junmai Ginjo 720ml", d: "Fukui's 'black dragon' — elegant, hard to find abroad.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 2750, f: 70000 },
  { id: "mio", n: "Mio Sparkling Sake 300ml", d: "Sweet sparkling sake, the perfect sake gateway.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 770, f: 50000 },
  { id: "onecup", n: "Ozeki One Cup Sake", d: "The iconic vending-machine sake cup. Peak Japan.", c: "Beverages", s: "FamilyMart", t: "tokyo", p: 250, f: 40000 },
  { id: "yamazaki12", n: "Yamazaki 12 Year 700ml", d: "The Japanese single malt. Allocation-only at home, gold overseas.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 33000, f: 100000, mk: 20 },
  { id: "hakushu12", n: "Hakushu 12 Year 700ml", d: "Forest-fresh single malt from Suntory's mountain distillery.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 33000, f: 100000, mk: 20 },
  { id: "nikka-ftb", n: "Nikka From The Barrel 500ml", d: "51.4% blended punch in the prettiest square bottle.", c: "Beverages", s: "Bic Camera Liquor", t: "tokyo", p: 4290, f: 70000 },
  { id: "nikka-coffey", n: "Nikka Coffey Grain 700ml", d: "Sweet, silky grain whisky from vintage Coffey stills.", c: "Beverages", s: "Bic Camera Liquor", t: "tokyo", p: 7150, f: 70000 },
  { id: "toki", n: "Suntory Toki 700ml", d: "Highball-ready blend, cheaper at the source.", c: "Beverages", s: "Bic Camera Liquor", t: "tokyo", p: 3300, f: 70000 },
  { id: "chita", n: "Suntory Chita Grain 700ml", d: "Feather-light grain whisky made for highballs.", c: "Beverages", s: "Bic Camera Liquor", t: "tokyo", p: 4400, f: 70000 },
  { id: "ichiros", n: "Ichiro's Malt White Label 700ml", d: "Chichibu's cult craft whisky, entry bottle.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 3850, f: 70000 },
  { id: "choya-excellent", n: "Choya Excellent Umeshu 750ml", d: "Top-shelf umeshu aged with whole Nanko plums.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 2035, f: 60000 },
  { id: "yuzushu", n: "Umenoyado Yuzushu 720ml", d: "Fresh yuzu liqueur — sunshine in a bottle.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 1650, f: 60000 },
  { id: "aragoshi", n: "Aragoshi Umeshu 720ml", d: "Thick, pulpy plum liqueur you almost chew.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 1760, f: 60000 },
  { id: "rokugin", n: "Roku Japanese Gin 700ml", d: "Six botanicals of Japan in Suntory's hexagon bottle.", c: "Beverages", s: "Bic Camera Liquor", t: "tokyo", p: 4400, f: 70000 },
  { id: "kinobi", n: "Ki No Bi Kyoto Dry Gin 700ml", d: "Kyoto craft gin with yuzu, hinoki and gyokuro.", c: "Beverages", s: "Isetan Liquor", t: "tokyo", p: 5500, f: 70000 },
  { id: "asahi-jokki", n: "Asahi Nama Jokki Can (6 pk)", d: "The self-foaming beer can that went viral. Japan only.", c: "Beverages", s: "FamilyMart", t: "tokyo", p: 1650, f: 60000 },
  { id: "ippodo-matcha", n: "Ippodo Matcha", d: "Kyoto's 300-year-old tea house, ceremonial grades.", c: "Beverages", s: "Ippodo Marunouchi", t: "tokyo", p: 1620, vq: 1, v: [{ n: "Ummon 40g", p: 4320 }, { n: "Ikuyo 40g" }] },
  { id: "ippodo-hojicha", n: "Ippodo Hojicha Gokujo 100g", d: "Roasty, comforting hojicha from Kyoto masters.", c: "Beverages", s: "Ippodo Marunouchi", t: "tokyo", p: 864 },
  { id: "koyamaen", n: "Marukyu Koyamaen Matcha 40g", d: "Uji matcha that tea ceremonies actually use.", c: "Beverages", s: "Takashimaya Nihombashi", t: "tokyo", p: 2160, vq: 1, v: [{ n: "Isuzu" }, { n: "Wako", p: 3240 }] },
  { id: "tsujiri-latte", n: "Tsujiri Matcha Milk Mix", d: "Instant Kyoto matcha latte, dangerously drinkable.", c: "Beverages", s: "Kyoto Station", t: "tokyo", p: 1080 },
  { id: "lupicia", n: "Lupicia Flavored Tea Tin", d: "Japan's cult tea boutique — flavors that sell out seasonally.", c: "Beverages", s: "Lupicia Jiyugaoka", t: "tokyo", p: 1200, vq: 1, v: ["Momo Oolong Super Grade", "Sakura Vert", "Grapefruit Green"] },
  { id: "karelcapek", n: "Karel Capek Tea Gift Box", d: "Illustrated tea tins too cute to open.", c: "Beverages", s: "Karel Capek Kichijoji", t: "tokyo", p: 1620 },
  { id: "arabica-beans", n: "% Arabica Kyoto Blend 200g", d: "Beans from the Kyoto roastery with the world's prettiest latte art.", c: "Beverages", s: "% Arabica Higashiyama", t: "tokyo", p: 1900 },
  { id: "ucc-drip", n: "UCC Craftsman Drip Coffee (50 pk)", d: "Bulk drip-bag coffee, Japan office fuel.", c: "Beverages", s: "Don Quijote Shinjuku", t: "tokyo", p: 1780 },
  { id: "ramune-hata", n: "Hata Ramune Original (6 btl)", d: "The classic marble-pop soda in glass bottles.", c: "Beverages", s: "Don Quijote Shinjuku", t: "tokyo", p: 780, f: 50000 },
  { id: "calpico", n: "Calpico Concentrate 470ml", d: "Dilute-at-home Calpis, the taste of Japanese summer.", c: "Beverages", s: "Don Quijote Shinjuku", t: "tokyo", p: 460, vq: 1, v: ["Original", "White Peach"] },
  { id: "yakult1000", n: "Yakult 1000 (7 pk)", d: "The viral sleep-better Yakult, Japan exclusive.", c: "Beverages", s: "FamilyMart", t: "tokyo", p: 910 },
  { id: "pocari-powder", n: "Pocari Sweat Powder (10 pk)", d: "Make Pocari anywhere — hoarder favorite.", c: "Beverages", s: "Matsumoto Kiyoshi", t: "tokyo", p: 1080 },
  { id: "japan-soda-set", n: "Japan-Only Soda Set (8 cans)", d: "Seasonal Fanta, Pepsi and oddball sodas in one box.", c: "Beverages", s: "Don Quijote Shinjuku", t: "tokyo", p: 1400, f: 50000 },
  { id: "jinro-soju", n: "Jinro Flavored Soju", d: "Korea's favorite fruit sojus, fresher at the source.", c: "Beverages", s: "Emart Seoul", t: "seoul", p: 1900, f: 60000, vq: 1, v: ["Green Grape", "Strawberry", "Plum"] },
  { id: "bokbunja", n: "Bohae Bokbunja 375ml", d: "Korean black raspberry wine, sweet and moreish.", c: "Beverages", s: "Emart Seoul", t: "seoul", p: 8900, f: 60000 },
  { id: "vita500", n: "Kwangdong Vita500 (10 btl)", d: "Korea's vitamin-C energy shot in the yellow bottle.", c: "Beverages", s: "Emart Seoul", t: "seoul", p: 7500 },
  { id: "bananamilk", n: "Binggrae Banana Milk (6 pk)", d: "The chubby-bottle banana milk of every K-drama.", c: "Beverages", s: "GS25 Seoul", t: "seoul", p: 9000 },
  { id: "maxim", n: "Maxim Mocha Gold (100 sticks)", d: "Korea's office coffee, hoarded by the boxful.", c: "Beverages", s: "Emart Seoul", t: "seoul", p: 19800 },
  { id: "osulloc", n: "Osulloc Tea Gift Set", d: "Jeju island tea in Korea's most giftable packaging.", c: "Beverages", s: "Osulloc Myeongdong", t: "seoul", p: 24000, vq: 1, v: ["Sejak", "Honey Pearl"] },

  // ================= SKINCARE & BEAUTY =================
  { id: "hadalabo-var", n: "Hada Labo Gokujyun", d: "More of the hyaluronic family everyone repurchases.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 1200, vq: 1, v: ["Premium Lotion", "Light Lotion", "Milk"] },
  { id: "melanocc", n: "Melano CC Vitamin C", d: "Japan's budget vitamin-C hero line.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 1210, vq: 1, v: ["Essence", "Premium Essence", "Lotion"] },
  { id: "biore-uv", n: "Biore UV Sunscreen", d: "Watery Japanese sunscreens that never feel like sunscreen.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 880, vq: 1, v: ["Aqua Rich Essence", "Athlizm Milk"] },
  { id: "anessa", n: "Anessa Perfect UV", d: "Shiseido's gold-standard beach sunscreen.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 3300, vq: 1, v: ["Gold Milk", "White Gel"] },
  { id: "skinaqua", n: "Skin Aqua Tone Up UV", d: "Lavender tone-up sunscreen, selfie-approved.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 990 },
  { id: "dhc-lip", n: "DHC Lip Cream", d: "Olive-oil lip balm with a permanent cult following.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 770 },
  { id: "dhc-oil", n: "DHC Deep Cleansing Oil 200ml", d: "The original olive cleansing oil since 1972.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 2724 },
  { id: "softymo", n: "Kose Softymo Speedy Cleansing Oil", d: "No-rinse-fuss drugstore cleansing oil.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 880 },
  { id: "curel", n: "Curel Intensive Moisture", d: "Ceramide care for sensitive skin, dermatologist favorite.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 1980, vq: 1, v: ["Foaming Wash", "Cream"] },
  { id: "kikumasamune", n: "Kikumasamune Sake Lotion 500ml", d: "Skincare made by a sake brewery. Huge bottle, cult item.", c: "Skincare", s: "Don Quijote Shinjuku", t: "tokyo", p: 924 },
  { id: "hatomugi", n: "Naturie Hatomugi Lotion 500ml", d: "Job's tears mega-bottle toner for full-body splashing.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 715 },
  { id: "lululun", n: "Lululun Daily Mask (32 pk)", d: "Japan's daily sheet mask in fridge-sized packs.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 1870, vq: 1, v: ["Pink Balance", "Blue Moisture", "Precious Red"] },
  { id: "minon", n: "Minon Amino Moist", d: "Amino-acid care for the most sensitive skin.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 2090, vq: 1, v: ["Charged Lotion", "Milky Cream"] },
  { id: "perfectwhip", n: "Senka Perfect Whip Cleanser", d: "Japan's best-selling foaming face wash.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 550 },
  { id: "obagi", n: "Obagi Vitamin C Serum", d: "Potent pharmacy vitamin C, strength-graded.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 3300, vq: 1, v: [{ n: "C10" }, { n: "C25", p: 11000 }] },
  { id: "transino", n: "Transino Whitening", d: "Japan's clinical brightening line.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 2860, vq: 1, v: ["White C Clear Serum", "Clear Wash"] },
  { id: "kiss-me-heroine", n: "Kiss Me Heroine Make Mascara", d: "The waterproof mascara that survives everything.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 1320 },
  { id: "canmake", n: "Canmake Tokyo Essentials", d: "Japan's beloved budget makeup, always sold out.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 850, vq: 1, v: ["Cream Cheek", "Marshmallow Powder", "Mermaid UV Gel"] },
  { id: "cezanne", n: "Cezanne Pearl Glow Highlighter", d: "The 600-yen highlighter beauty editors hoard.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 660 },
  { id: "rohto-lycee", n: "Rohto Lycee Eye Drops", d: "Pink eye drops that de-red tired eyes instantly.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 850 },
  { id: "megrhythm", n: "MegRhythm Steam Eye Mask (12 pk)", d: "Self-warming lavender eye masks for flights.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 1300 },
  { id: "lulucos", n: "Excel Skinny Rich Eyeshadow", d: "Japan's most praised drugstore eyeshadow quad.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 1650 },
  { id: "shigaisen", n: "Shigaisen Yohou UV Stick", d: "Clear sunscreen stick for lazy reapplication.", c: "Skincare", s: "Ainz & Tulpe", t: "tokyo", p: 2860 },
  { id: "ettusais", n: "Ettusais Lip Essence Stick", d: "Night lip treatment with a devoted Japan fanbase.", c: "Skincare", s: "Ainz & Tulpe", t: "tokyo", p: 1320 },
  { id: "keana", n: "Keana Nadeshiko Rice Mask (10 pk)", d: "Rice-serum pore masks, permanently trending.", c: "Skincare", s: "Matsumoto Kiyoshi", t: "tokyo", p: 715 },
  { id: "medicube-var", n: "Medicube", d: "More from the glass-skin brand.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 26000, vq: 1, v: ["Zero Pore Pads 2.0", "Collagen Jelly Cream", "Deep Vita C Capsule Cream"] },
  { id: "anua-var", n: "Anua Heartleaf", d: "The heartleaf line beyond the famous oil.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 18000, vq: 1, v: ["77% Soothing Toner", "Niacinamide Serum", "Pore Control Foam"] },
  { id: "cosrx", n: "COSRX Essentials", d: "K-beauty's no-nonsense workhorses.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 17000, vq: 1, v: ["Snail 96 Essence", "Low pH Cleanser", "Vitamin C 23 Serum"] },
  { id: "boj", n: "Beauty of Joseon", d: "Hanbang skincare that conquered TikTok.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 15000, vq: 1, v: ["Relief Sun SPF50", "Glow Serum", "Ginseng Cleansing Oil"] },
  { id: "torriden", n: "Torriden Dive-In", d: "Korea's minimalist hydration line.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 16000, vq: 1, v: ["Serum", "Toner"] },
  { id: "roundlab", n: "Round Lab", d: "Olive Young bestseller shelf regulars.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 16000, vq: 1, v: ["1025 Dokdo Toner", "Birch Juice Sunscreen"] },
  { id: "skin1004", n: "Skin1004 Centella", d: "Madagascar centella for angry skin.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 15500, vq: 1, v: ["Ampoule", "Hyalu-Cica Sun Serum"] },
  { id: "mixsoon", n: "Mixsoon Bean Essence 50ml", d: "The fermented bean essence with a chokehold on K-beauty.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 22000 },
  { id: "abib", n: "Abib Gummy Sheet Mask (10 pk)", d: "The jelly-adhesion masks that hug your face.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 27000 },
  { id: "mediheal", n: "Mediheal Mask Box (10 pk)", d: "Korea's pharmacy mask in bulk boxes.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 12000, vq: 1, v: ["Tea Tree", "Collagen", "Madecassoside"] },
  { id: "numbuzin", n: "Numbuzin Serum", d: "The numbered serums Koreans rank religiously.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 21000, vq: 1, v: ["No.3 Glow", "No.5 Vitamin"] },
  { id: "goodal", n: "Goodal Green Tangerine Vita C Serum", d: "Jeju tangerine brightening, gentle enough for daily use.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 18000 },
  { id: "isntree", n: "Isntree Hyaluronic Toner 400ml", d: "A liter-adjacent bottle of pure hydration.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 19000 },
  { id: "manyo", n: "Ma:nyo Pure Cleansing Oil 200ml", d: "Korea's #1 cleansing oil by units sold.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 19500 },
  { id: "laneige-var", n: "Laneige", d: "More Laneige icons at Korea prices.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 25000, vq: 1, v: ["Water Bank Cream", "Cream Skin Toner", "Bouncy & Firm Sleeping Mask"] },
  { id: "sulwhasoo", n: "Sulwhasoo First Care Serum 60ml", d: "Korea's luxury hanbang serum, duty-free darling.", c: "Skincare", s: "Lotte Duty Free", t: "seoul", p: 76000, mk: 18 },
  { id: "hera-cushion", n: "Hera Black Cushion", d: "The K-drama cushion foundation.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 40000 },
  { id: "drjart", n: "Dr.Jart+ Cicapair", d: "Green-to-beige redness rescue.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 28000, vq: 1, v: ["Tiger Grass Cream", "Color Correcting Treatment"] },
  { id: "rom-nd", n: "Rom&nd Juicy Lasting Tint", d: "The glassy K-lip tint in bestseller shades.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 9900, vq: 1, v: ["Fig Fig", "Apple Brown", "Bare Grape"] },
  { id: "clio-kill", n: "Clio Kill Cover Cushion", d: "Korea's full-coverage cushion king.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 22000 },
  { id: "tirtir", n: "TirTir Mask Fit Red Cushion", d: "The viral red cushion in 40 shades.", c: "Skincare", s: "Olive Young Myeongdong", t: "seoul", p: 24000 },

  // ================= FRAGRANCE =================
  { id: "shiro-var", n: "SHIRO Eau de Parfum 40ml", d: "SHIRO's clean-scent lineup beyond Savon.", c: "Fragrance", s: "SHIRO Aoyama", t: "tokyo", p: 5280, vq: 1, v: ["White Tea", "Kinmokusei", "Earl Grey", "Sabon Iris"] },
  { id: "shiro-mist", n: "SHIRO Body Mist", d: "Lighter SHIRO scents for everyday spritzing.", c: "Fragrance", s: "SHIRO Aoyama", t: "tokyo", p: 3080, vq: 1, v: ["Savon", "White Lily", "White Tea"] },
  { id: "shiro-hand", n: "SHIRO Hand Serum", d: "The gift-ready hand care in SHIRO's cult scents.", c: "Fragrance", s: "SHIRO Aoyama", t: "tokyo", p: 2530, vq: 1, v: ["Savon", "Kinmokusei"] },
  { id: "jscent-var", n: "J-Scent Eau de Parfum 50ml", d: "Tokyo niche house bottling very Japanese memories.", c: "Fragrance", s: "@cosme TOKYO Harajuku", t: "tokyo", p: 4950, vq: 1, v: ["Hisui", "Paper Soap", "Yuzu", "Sumo Wrestler", "Hanamizake", "Wagashi", "Koke (Moss)"] },
  { id: "auxparadis-var", n: "Aux Paradis Eau de Parfum 30ml", d: "Minimal Japanese perfumery, nature-first scents.", c: "Fragrance", s: "Aux Paradis Omotesando", t: "tokyo", p: 3300, vq: 1, v: ["Fleur", "Peach", "Sakura", "Vanilla", "Eau de Savon"] },
  { id: "cdgparfum-var", n: "CDG Parfums", d: "Comme des Garçons' experimental scent lab.", c: "Fragrance", s: "Dover Street Market Ginza", t: "tokyo", p: 13200, mk: 20, vq: 1, v: ["CDG2", "Black Pepper", "Amazingreen", "Kyoto (Series 3)", "Concrete", "Floriental"] },
  { id: "satori", n: "Parfum Satori 40ml", d: "Haute Japanese perfumery from a Tokyo atelier.", c: "Fragrance", s: "Satori Ginza Atelier", t: "tokyo", p: 14300, mk: 20, vq: 1, v: ["Satori", "Iris Homme", "Hyouge"] },
  { id: "diser", n: "DI SER Eau de Parfum 30ml", d: "Sapporo's all-botanical niche house.", c: "Fragrance", s: "Nose Shop Shinjuku", t: "tokyo", p: 13200, mk: 20, vq: 1, v: ["Kyara", "Sora"] },
  { id: "isseyleau", n: "Issey Miyake L'Eau d'Issey 50ml", d: "The Japanese design-classic scent, home pricing.", c: "Fragrance", s: "Isetan Shinjuku", t: "tokyo", p: 8800, vq: 1, v: ["Pour Homme", "Pour Femme"] },
  { id: "uka-nail", n: "Uka Nail Oil", d: "Tokyo salon's scented nail oils, perfect small gift.", c: "Fragrance", s: "Uka Tokyo Midtown", t: "tokyo", p: 3630, vq: 1, v: ["7:15", "24:45"] },
  { id: "tamburins-var", n: "Tamburins", d: "Seoul's gallery-like scent brand.", c: "Fragrance", s: "Tamburins Hannam Seoul", t: "seoul", p: 42000, vq: 1, v: ["Egg Perfume Chamo", "Perfume Balm Pumkini", "Hand Cream 000", "Big Hand Cream Berga Sandal"] },
  { id: "nonfiction", n: "Nonfiction Eau de Parfum 100ml", d: "Korea's minimalist luxury scent house.", c: "Fragrance", s: "Nonfiction Hannam", t: "seoul", p: 135000, mk: 20, vq: 1, v: ["Santal Cream", "Gentle Night", "For Rest"] },
  { id: "granhand", n: "Granhand Multi Perfume 100ml", d: "Seoul's beloved paper-wrapped fragrance shop.", c: "Fragrance", s: "Granhand Bukchon", t: "seoul", p: 38000, vq: 1, v: ["Roland", "Marine Orchid", "Troublesome"] },
  { id: "forment", n: "Forment Cotton Perfume 50ml", d: "The 'fabric softener' scent all of Korea wears.", c: "Fragrance", s: "Olive Young Myeongdong", t: "seoul", p: 39000, vq: 1, v: ["Cotton Hug", "Cotton Kiss"] },

  // ================= FASHION =================
  { id: "uniqlo-airism", n: "Uniqlo Airism Cotton Tee", d: "The invisible-comfort tee Japan buys in bulk.", c: "Fashion", s: "Uniqlo Ginza", t: "tokyo", p: 1500, vq: 1, v: ["White", "Black", "Olive"] },
  { id: "uniqlo-u-tee", n: "Uniqlo U Crew Neck Tee", d: "Lemaire-designed boxy tee, always first to sell out.", c: "Fashion", s: "Uniqlo Ginza", t: "tokyo", p: 1990, vq: 1, v: ["White", "Black", "Brown"] },
  { id: "uniqlo-uld", n: "Uniqlo Ultra Light Down Jacket", d: "Packable warmth that fits in its own pouch.", c: "Fashion", s: "Uniqlo Ginza", t: "tokyo", p: 6990, vq: 1, v: ["Navy", "Black", "Olive"] },
  { id: "uniqlo-cashmere", n: "Uniqlo 100% Cashmere Crew", d: "Real cashmere at Uniqlo prices — Japan stock runs deep.", c: "Fashion", s: "Uniqlo Ginza", t: "tokyo", p: 9990, vq: 1, v: ["Grey", "Camel"] },
  { id: "uniqlo-flannel", n: "Uniqlo Flannel Shirt", d: "The autumn staple, better colorways in Japan.", c: "Fashion", s: "Uniqlo Ginza", t: "tokyo", p: 2990 },
  { id: "uniqlo-ut", n: "Uniqlo UT Collab Tee", d: "Japan-first artist and anime collab tees.", c: "Fashion", s: "Uniqlo Ginza", t: "tokyo", p: 1990, vq: 1, v: ["One Piece", "Kaws Tokyo First", "Murakami Flower", "Jujutsu Kaisen"] },
  { id: "gu-basics", n: "GU Trend Basics", d: "Uniqlo's cheaper, trendier sibling — Japan only.", c: "Fashion", s: "GU Shibuya", t: "tokyo", p: 2490, vq: 1, v: ["Barrel Leg Jeans", "Heavy Sweat Hoodie", "Pleated Wide Pants"] },
  { id: "cdgplay-var", n: "CDG Play Tee", d: "More heart-logo colorways from the source.", c: "Fashion", s: "Dover Street Market Ginza", t: "tokyo", p: 9000, mk: 25, vq: 1, v: ["Black", "Navy", "Grey", "Red Heart Black"] },
  { id: "cdgplay-cardigan", n: "CDG Play Cardigan", d: "The heart-patch wool cardigan, made in Japan.", c: "Fashion", s: "Dover Street Market Ginza", t: "tokyo", p: 29700, mk: 22, vq: 1, v: ["Black", "Navy"] },
  { id: "humanmade-var", n: "Human Made", d: "NIGO's vintage-Americana staples.", c: "Fashion", s: "Human Made Shibuya", t: "tokyo", p: 13200, mk: 22, vq: 1, v: ["Polar Bear Tee", "Duck Hoodie", "Heart Chino Cap", "Bandana"] },
  { id: "beams-var", n: "BEAMS Japan", d: "More of the orange-label Japan pride line.", c: "Fashion", s: "BEAMS Japan Shinjuku", t: "tokyo", p: 6600, vq: 1, v: ["Logo Cap", "Souvenir Tote", "Fuji Tee"] },
  { id: "wtaps", n: "WTAPS Tee", d: "Tokyo military-streetwear, domestic allocation.", c: "Fashion", s: "GIP-STORE Harajuku", t: "tokyo", p: 9900, mk: 25, vq: 1, v: ["Black", "Olive"] },
  { id: "neighborhood", n: "Neighborhood Logo Tee", d: "Harajuku's motorcycle-culture original.", c: "Fashion", s: "Neighborhood Harajuku", t: "tokyo", p: 8800, mk: 25, vq: 1, v: ["Black", "White"] },
  { id: "kapital-socks", n: "Kapital Smiley Socks", d: "The heel-smiley socks with a global cult.", c: "Fashion", s: "Kapital Ebisu", t: "tokyo", p: 2530, mk: 30, vq: 1, v: ["Ivory", "Navy", "Red"] },
  { id: "needles-track", n: "Needles Track Pant", d: "The butterfly track pants of every fit pic.", c: "Fashion", s: "Nepenthes Tokyo", t: "tokyo", p: 24200, mk: 20, vq: 1, v: ["Navy Straight", "Black Narrow", "Purple Boot-Cut"] },
  { id: "fr2", n: "#FR2 Smoking Kills Tee", d: "Harajuku's provocative rabbit brand, Japan exclusive drops.", c: "Fashion", s: "#FR2 Harajuku", t: "tokyo", p: 7150, mk: 25, vq: 1, v: ["Black", "White", "Box Logo"] },
  { id: "montbell", n: "Mont-bell", d: "Japan's outdoor giant — half the price of abroad.", c: "Fashion", s: "Mont-bell Shibuya", t: "tokyo", p: 13500, mk: 18, vq: 1, v: ["Versalite Jacket", "Plasma 1000 Down", "Chameece Jacket"] },
  { id: "snowpeak-wear", n: "Snow Peak Flexible Insulated", d: "Camp-to-city technical wear from Niigata.", c: "Fashion", s: "Snow Peak Harajuku", t: "tokyo", p: 22000, mk: 18, vq: 1, v: ["Pullover", "Pants"] },
  { id: "gramicci", n: "Gramicci Climbing Pant", d: "The gusseted everyday pants Japan standardized.", c: "Fashion", s: "BEAMS Harajuku", t: "tokyo", p: 8800, vq: 1, v: ["Olive", "Black", "Beige", "Navy"] },
  { id: "tabio", n: "Tabio Japanese Socks", d: "Japan's finest sock maker, ridiculous quality.", c: "Fashion", s: "Tabio Shibuya", t: "tokyo", p: 1430, mk: 30, vq: 1, v: ["Ribbed Wool", "Tabi Split-Toe", "Pile Room Socks"] },
  { id: "muji-basics", n: "MUJI Wardrobe Basics", d: "The quiet essentials MUJI does best.", c: "Fashion", s: "MUJI Ginza", t: "tokyo", p: 2990, vq: 1, v: ["Oxford Shirt", "Sweatshirt", "Linen Shirt"] },
  { id: "aderror", n: "Ader Error Logo Piece", d: "Seoul's art-school streetwear darling.", c: "Fashion", s: "Ader Error Seongsu", t: "seoul", p: 98000, mk: 22, vq: 1, v: ["Tee", "Beanie"] },
  { id: "matinkim", n: "Matin Kim", d: "The it-girl Seoul brand with permanent queues.", c: "Fashion", s: "Matin Kim Hannam", t: "seoul", p: 59000, mk: 25, vq: 1, v: ["Logo Tee", "Ball Cap", "Mini Bag", "Knit Zip-Up"] },
  { id: "mardi", n: "Mardi Mercredi Flower Tee", d: "Korea's flower-logo phenomenon, jastip bestseller.", c: "Fashion", s: "Mardi Mercredi Apgujeong", t: "seoul", p: 49000, mk: 25, vq: 1, v: ["White/Navy", "Cream/Red", "Black/White", "Sweatshirt Ivory"] },
  { id: "covernat", n: "Covernat Authentic Logo", d: "Clean Korean casual with wallet-friendly prices.", c: "Fashion", s: "Covernat Hongdae", t: "seoul", p: 39000, vq: 1, v: ["Tee", "Hoodie"] },
  { id: "thisisneverthat", n: "Thisisneverthat T-Logo", d: "Seoul streetwear in its natural habitat.", c: "Fashion", s: "Thisisneverthat Hannam", t: "seoul", p: 42000, vq: 1, v: ["Tee", "Cap", "Crewneck"] },
  { id: "emis", n: "EMIS New Logo Ball Cap", d: "The K-celeb cap brand, always low stock.", c: "Fashion", s: "EMIS Hannam", t: "seoul", p: 42000, mk: 25, vq: 1, v: ["Beige", "Black", "Pink"] },
  { id: "mlb-korea", n: "MLB Korea Cap", d: "The Korea-only MLB fashion line, NY monogram era.", c: "Fashion", s: "MLB Myeongdong", t: "seoul", p: 39000, vq: 1, v: ["NY Black", "NY Beige", "LA Cream"] },

  // ================= SHOES =================
  { id: "mexico66-var", n: "Onitsuka Tiger Mexico 66", d: "The Kill Bill classic in Japan-exclusive colorways.", c: "Shoes", s: "Onitsuka Tiger Ginza", t: "tokyo", p: 15400, vq: 1, colors: [{n:"Yellow/Black",h:"#F5D30F"},{n:"White/Blue",h:"#4A90D9"},{n:"Birch/Green",h:"#6B8E4E"},{n:"Black/White",h:"#1A1A1A"},{n:"Silver/Red",h:"#C0392B"},{n:"Cream/Peacoat",h:"#2C3E50"}], v: ["Yellow/Black", "White/Blue", "Birch/Green", "Black/White", "Silver/Red", "Cream/Peacoat"] },
  { id: "onitsuka-serrano", n: "Onitsuka Tiger Serrano", d: "The slimmer, sleeker sibling of Mexico 66.", c: "Shoes", s: "Onitsuka Tiger Ginza", t: "tokyo", p: 12100, vq: 1, colors: [{n:"Black/White",h:"#1A1A1A"},{n:"Cream/Navy",h:"#2C3E50"},{n:"Green/Yellow",h:"#4CAF50"}], v: ["Black/White", "Cream/Navy", "Green/Yellow"] },
  { id: "onitsuka-tokuten", n: "Onitsuka Tiger Tokuten", d: "Vintage soccer trainer revived, Japan stock.", c: "Shoes", s: "Onitsuka Tiger Ginza", t: "tokyo", p: 9900, vq: 1, colors: [{n:"White/Green",h:"#4CAF50"},{n:"Black/Gold",h:"#D4A843"}], v: ["White/Green", "Black/Gold"] },
  { id: "kayano14-var", n: "Asics Gel-Kayano 14", d: "More of the Y2K runner in fresh colorways.", c: "Shoes", s: "ABC Mart Harajuku", t: "tokyo", p: 17600, vq: 1, colors: [{n:"White/Midnight",h:"#191970"},{n:"Black/Pure Silver",h:"#C0C0C0"},{n:"Cream/Peach",h:"#FFDAB9"}], v: ["White/Midnight", "Black/Pure Silver", "Cream/Peach"] },
  { id: "asics-gt2160", n: "Asics GT-2160", d: "The next retro-tech silhouette blowing up.", c: "Shoes", s: "ABC Mart Harajuku", t: "tokyo", p: 14300, vq: 1, colors: [{n:"White/Silver",h:"#C0C0C0"},{n:"Black/Yellow",h:"#F5D30F"},{n:"Grey/Blue",h:"#4A90D9"}], v: ["White/Silver", "Black/Yellow", "Grey/Blue"] },
  { id: "asics-gelnyc", n: "Asics Gel-NYC", d: "Chunky comfort with 2000s DNA.", c: "Shoes", s: "ABC Mart Harajuku", t: "tokyo", p: 15400, vq: 1, colors: [{n:"Cream/Oyster",h:"#E8DCC8"},{n:"Graphite/Smoke",h:"#5A5A5A"}], v: ["Cream/Oyster", "Graphite/Smoke"] },
  { id: "asics-gel1130", n: "Asics Gel-1130", d: "The budget-friendly retro runner everyone owns now.", c: "Shoes", s: "ABC Mart Harajuku", t: "tokyo", p: 11000, vq: 1, colors: [{n:"White/Cloud",h:"#F5F5F5"},{n:"Black/Carrier Grey",h:"#555555"},{n:"Birch",h:"#D2C6A5"}], v: ["White/Cloud", "Black/Carrier Grey", "Birch"] },
  { id: "asics-japan-s", n: "Asics Japan S", d: "Clean court shoe, Tokyo wardrobe default.", c: "Shoes", s: "ABC Mart Harajuku", t: "tokyo", p: 8800, vq: 1, colors: [{n:"White/Black",h:"#1A1A1A"},{n:"White/Green",h:"#4CAF50"}], v: ["White/Black", "White/Green"] },
  { id: "nb2002r", n: "New Balance 2002R", d: "The premium comfort daily, JP allocation.", c: "Shoes", s: "New Balance Harajuku", t: "tokyo", p: 19800, vq: 1, colors: [{n:"Rain Cloud",h:"#B8BFC6"},{n:"Black",h:"#1A1A1A"},{n:"Protection Pack Grey",h:"#8B8B8B"}], v: ["Rain Cloud", "Black", "Protection Pack Grey"] },
  { id: "nb530", n: "New Balance 530", d: "Silver-mesh Y2K icon, cheaper in Japan.", c: "Shoes", s: "ABC Mart Harajuku", t: "tokyo", p: 12100, vq: 1, colors: [{n:"White/Silver",h:"#C0C0C0"},{n:"White/Navy",h:"#2C3E50"}], v: ["White/Silver", "White/Navy"] },
  { id: "nb990v6", n: "New Balance 990v6 (USA)", d: "The made-in-USA flagship, JP tax-free price.", c: "Shoes", s: "New Balance Ginza", t: "tokyo", p: 30800, mk: 15, vq: 1, colors: [{n:"Grey",h:"#808080"},{n:"Navy",h:"#2C3E50"}], v: ["Grey", "Navy"] },
  { id: "converse-jp", n: "Converse Japan All Star J", d: "Made-in-Japan Converse — different license, better build.", c: "Shoes", s: "ABC Mart Harajuku", t: "tokyo", p: 13200, vq: 1, colors: [{n:"Hi Black",h:"#1A1A1A"},{n:"Hi Natural White",h:"#FAF0E6"},{n:"Ox White",h:"#FFFFFF"}], v: ["Hi Black", "Hi Natural White", "Ox White"] },
  { id: "converse-onestar", n: "Converse Japan One Star J", d: "Suede one-star, Japan-license exclusive.", c: "Shoes", s: "Billy's Tokyo", t: "tokyo", p: 14300, vq: 1, colors: [{n:"Black",h:"#1A1A1A"},{n:"Navy",h:"#2C3E50"}], v: ["Black", "Navy"] },
  { id: "moonstar", n: "Moonstar 810s", d: "Kurume-made rubber shoes, quiet design-lover hit.", c: "Shoes", s: "1LDK Nakameguro", t: "tokyo", p: 7700, vq: 1, colors: [{n:"Kitchen White",h:"#FFFFFF"},{n:"Marke Black",h:"#1A1A1A"},{n:"Hospi Grey",h:"#A0A0A0"}], v: ["Kitchen White", "Marke Black", "Hospi Grey"] },
  { id: "mizuno-racer", n: "Mizuno Wave Rider 10 OG", d: "Japan's own runner heritage, reissued.", c: "Shoes", s: "ABC Mart Harajuku", t: "tokyo", p: 14300, vq: 1, colors: [{n:"Silver/Blue",h:"#4A90D9"},{n:"White/Red",h:"#C0392B"}], v: ["Silver/Blue", "White/Red"] },
  { id: "excelsior", n: "Excelsior Bolt Sneaker", d: "Korea's canvas-sneaker answer to Converse.", c: "Shoes", s: "Excelsior Hongdae", t: "seoul", p: 69000, vq: 1, colors: [{n:"Ecru",h:"#F5F0E1"},{n:"Black",h:"#1A1A1A"},{n:"Mustard",h:"#E1A95F"}], v: ["Ecru", "Black", "Mustard"] },

  // ================= ELECTRONICS =================
  { id: "x100vi-silver", n: "Fujifilm X100VI (Silver)", d: "The silver version of the sold-out icon.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 280000, mk: 12, f: 150000 },
  { id: "ricoh-gr3x", n: "Ricoh GR IIIx", d: "Street photography's pocket king, 40mm.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 160000, mk: 12, f: 120000 },
  { id: "ricoh-gr3", n: "Ricoh GR III", d: "The 28mm original, perpetually backordered.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 150000, mk: 12, f: 120000 },
  { id: "canon-g7x", n: "Canon PowerShot G7X Mark III", d: "The vlog compact TikTok made unbuyable.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 120000, mk: 12, f: 100000 },
  { id: "instax-mini12", n: "Fujifilm Instax Mini 12", d: "Everyone's first instant camera.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 8900, vq: 1, v: ["Lilac Purple", "Mint Green", "Blossom Pink", "Clay White"] },
  { id: "instax-evo", n: "Fujifilm Instax Mini Evo", d: "Hybrid instax with retro dials — print only the good ones.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 26400, vq: 1, v: ["Black", "Brown"] },
  { id: "instax-film", n: "Instax Mini Film", d: "Film packs, way cheaper in Japan.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 1180, vq: 1, v: ["Twin Pack", "Contact Sheet", "Rainbow"] },
  { id: "sony-wh1000xm6", n: "Sony WH-1000XM6 Headphones", d: "The new flagship noise-cancel over-ears.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 59400, mk: 15, vq: 1, v: ["Black", "Platinum Silver"] },
  { id: "technics-az80", n: "Technics EAH-AZ80", d: "Audiophile earbuds with triple-device pairing.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 36300, mk: 15 },
  { id: "audiotechnica", n: "Audio-Technica ATH-M50x", d: "The studio standard, home-market price.", c: "Electronics", s: "e-earphone Akihabara", t: "tokyo", p: 16500, vq: 1, v: ["Black", "White"] },
  { id: "final-ze3000", n: "Final ZE3000 Earbuds", d: "Tokyo boutique audio brand, hi-fi tuning.", c: "Electronics", s: "e-earphone Akihabara", t: "tokyo", p: 15800 },
  { id: "switch2-procon", n: "Switch 2 Pro Controller", d: "The essential Switch 2 upgrade.", c: "Electronics", s: "Yodobashi Akihabara", t: "tokyo", p: 9980 },
  { id: "switch2-games", n: "Switch 2 Game (JP Cart)", d: "Japanese carts play in any language.", c: "Electronics", s: "Yodobashi Akihabara", t: "tokyo", p: 7980, vq: 1, v: ["Kirby Air Riders", "Donkey Kong Bananza", "Pokemon Legends Z-A", "Splatoon Raiders"] },
  { id: "gameandwatch", n: "Game & Watch: Super Mario Bros", d: "Nintendo's retro handheld reissue.", c: "Electronics", s: "Yodobashi Akihabara", t: "tokyo", p: 5478 },
  { id: "refa", n: "ReFa Beauty Device", d: "Japan's salon-at-home beauty tech.", c: "Electronics", s: "Loft Shibuya", t: "tokyo", p: 26400, mk: 15, vq: 1, v: ["Beautech Dryer Pro", "Straight Iron Pro", "Carat Face Roller", "Heart Brush"] },
  { id: "yaman", n: "Ya-man Facial Device", d: "RF and EMS facial tech Japan swears by.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 44000, mk: 15, vq: 1, v: ["Medi Lift", "Photo Plus Shiny"] },
  { id: "salonia", n: "SALONIA Straight Iron", d: "Japan's #1 budget hair iron.", c: "Electronics", s: "Loft Shibuya", t: "tokyo", p: 3828, vq: 1, v: ["15mm", "24mm"] },
  { id: "panasonic-var", n: "Panasonic Beauty", d: "More nanoe beauty appliances.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 19800, mk: 15, vq: 1, v: ["Steamer Nanocare", "Compact Steamer"] },
  { id: "gshock-var", n: "Casio G-Shock JDM", d: "Japan-domestic G-Shocks not exported.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 16500, vq: 1, v: ["DW-5600 Origin", "GA-2100 'CasiOak' Black", "GA-2100 Forest Green", "GMW-B5000 Steel"] },
  { id: "casio-fx", n: "Casio fx-JP900 Calculator", d: "The beautiful JDM scientific calculator. Nerd flex.", c: "Electronics", s: "Yodobashi Akihabara", t: "tokyo", p: 5980 },
  { id: "sony-a6700", n: "Sony a6700 Body", d: "APS-C do-everything body, tax-free Japan price.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 198000, mk: 12, f: 150000 },
  { id: "sigma-lens", n: "Sigma 18-50mm f/2.8 (E-mount)", d: "The compact zoom every hybrid shooter wants.", c: "Electronics", s: "Map Camera Shinjuku", t: "tokyo", p: 55000, mk: 12, f: 80000 },
  { id: "instax-wide", n: "Fujifilm Instax Wide Evo", d: "The wide-format hybrid instax, JP launch stock.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 49500, mk: 15 },
  { id: "keyboard-hhkb", n: "HHKB Professional Hybrid Type-S", d: "Tokyo's legendary programmer keyboard.", c: "Electronics", s: "Yodobashi Akihabara", t: "tokyo", p: 36850, mk: 15, vq: 1, v: ["Charcoal", "Snow White"] },
  { id: "sony-linkbuds", n: "Sony LinkBuds S", d: "All-day earbuds, JP colorways.", c: "Electronics", s: "Bic Camera Shinjuku", t: "tokyo", p: 24200, vq: 1, v: ["Black", "Earth Blue"] },

  // ================= TOYS & COLLECTIBLES =================
  { id: "labubu-var", n: "Labubu Blind Box", d: "More Labubu series while Tokyo still has stock.", c: "Collectibles", s: "Pop Mart Shibuya", t: "tokyo", p: 1980, mk: 25, vq: 1, v: ["Have a Seat", "Exciting Macaron", "Coca-Cola Series"] },
  { id: "crybaby-var", n: "Crybaby Blind Box", d: "More tears, more series.", c: "Collectibles", s: "Pop Mart Shibuya", t: "tokyo", p: 2200, mk: 25, vq: 1, v: ["Sad Club", "Powerpuff Girls Collab"] },
  { id: "skullpanda", n: "Skullpanda Blind Box", d: "Pop Mart's moody design icon.", c: "Collectibles", s: "Pop Mart Shibuya", t: "tokyo", p: 1980, mk: 25, vq: 1, v: ["Tempted Heart", "Image of Reality"] },
  { id: "molly", n: "Molly Blind Box", d: "The original Pop Mart girl.", c: "Collectibles", s: "Pop Mart Shibuya", t: "tokyo", p: 1980, mk: 25 },
  { id: "hirono", n: "Hirono Blind Box", d: "Melancholic little guy, huge resale.", c: "Collectibles", s: "Pop Mart Shibuya", t: "tokyo", p: 1980, mk: 25 },
  { id: "sonnyangel", n: "Sonny Angel Blind Box", d: "The cherub keeping Japan's blind-box shelves empty.", c: "Collectibles", s: "Kiddy Land Harajuku", t: "tokyo", p: 880, mk: 30, vq: 1, v: ["Animal Series 1", "Fruit Series", "Hippers"] },
  { id: "smiski", n: "Smiski Glow Figure", d: "Glow-in-the-dark corner gremlins.", c: "Collectibles", s: "Kiddy Land Harajuku", t: "tokyo", p: 880, mk: 30, vq: 1, v: ["Living Series", "Bath Series", "Yoga Series"] },
  { id: "gunpla-rg-var", n: "Bandai RG Gunpla", d: "Real Grade lineup beyond the RX-78-2.", c: "Toys", s: "Yodobashi Akihabara", t: "tokyo", p: 4180, vq: 1, v: ["Nu Gundam", "Sazabi", "Unicorn Gundam", "Strike Freedom", "00 Raiser"] },
  { id: "gunpla-mg", n: "Bandai MG Gunpla", d: "Master Grade builds for serious desks.", c: "Toys", s: "Yodobashi Akihabara", t: "tokyo", p: 5500, vq: 1, v: ["Freedom 2.0", "Barbatos", "Zaku II 2.0"] },
  { id: "gunpla-hg", n: "Bandai HG Gunpla", d: "High Grade entry kits, Japan restock pricing.", c: "Toys", s: "Yodobashi Akihabara", t: "tokyo", p: 1980, vq: 1, v: ["Aerial", "Calibarn", "Barbatos Lupus"] },
  { id: "gunpla-pg", n: "Bandai PG Unleashed RX-78-2", d: "The ultimate Gunpla. A furniture-sized project.", c: "Toys", s: "Yodobashi Akihabara", t: "tokyo", p: 27500, mk: 20, f: 100000 },
  { id: "pokeplush-var", n: "Pokémon Center Plush", d: "Center-exclusive plush beyond Pikachu.", c: "Toys", s: "Pokémon Center Shibuya", t: "tokyo", p: 2420, vq: 1, v: ["Eevee", "Snorlax", "Gengar", "Mimikyu", "Sylveon"] },
  { id: "pokemonfit", n: "Pokémon Fit Mini Plush", d: "Palm-sized plush of literally every Pokémon.", c: "Toys", s: "Pokémon Center Shibuya", t: "tokyo", p: 1320, vq: 1, v: ["Ditto", "Psyduck", "Magikarp"] },
  { id: "pokemontcg-var", n: "Pokémon TCG Japanese Box", d: "Newer Japanese sets, sealed.", c: "Collectibles", s: "Pokémon Center Shibuya", t: "tokyo", p: 5940, mk: 30, vq: 1, v: ["Terastal Festival", "Heat Wave Arena", "Black Bolt"] },
  { id: "sanrio-var", n: "Sanrio Character Plush", d: "The rest of the Sanrio cinematic universe.", c: "Toys", s: "Sanrio Gift Gate", t: "tokyo", p: 3850, vq: 1, v: ["Kuromi", "Cinnamoroll", "My Melody", "Pompompurin", "Pochacco"] },
  { id: "sanrio-goods", n: "Sanrio Accessories", d: "Small Sanrio things that vanish from shelves.", c: "Toys", s: "Sanrio Gift Gate", t: "tokyo", p: 1650, vq: 1, v: ["Pouch", "Keychain Set", "Mini Towel"] },
  { id: "ghibli-var", n: "Studio Ghibli (Donguri)", d: "Official Ghibli goods from Donguri Kyowakoku.", c: "Toys", s: "Donguri Kyowakoku Skytree", t: "tokyo", p: 3080, vq: 1, v: ["Totoro Plush M", "Jiji Plush", "Calcifer Ladle Rest", "Kodama Figure Set"] },
  { id: "nanoblock", n: "Nanoblock Japan Landmark", d: "Micro-brick kits of very Japanese things.", c: "Toys", s: "Tokyu Hands Shibuya", t: "tokyo", p: 2530, vq: 1, v: ["Tokyo Tower", "Torii Gate", "Sushi Set"] },
  { id: "tomica", n: "Tomica Premium Die-cast", d: "Japan's die-cast obsession, JDM cars included.", c: "Toys", s: "Yodobashi Akihabara", t: "tokyo", p: 1100, vq: 1, v: ["Nissan GT-R", "Toyota AE86", "Initial D Set"] },
  { id: "sylvanian", n: "Sylvanian Families JP Exclusive", d: "Japan-only Sylvanian sets and babies.", c: "Toys", s: "Kiddy Land Harajuku", t: "tokyo", p: 2750, vq: 1, v: ["Baby Trio", "Chocolate Rabbit Family"] },
  { id: "bearbrick", n: "Be@rbrick 400%", d: "Medicom's collectible bear, Tokyo drops.", c: "Collectibles", s: "Medicom Toy Plus Shibuya", t: "tokyo", p: 15400, mk: 25, vq: 1, v: ["Clear Chrome", "Andy Warhol"] },
  { id: "nendoroid", n: "Nendoroid Figure", d: "Good Smile's chibi figures, JP release price.", c: "Collectibles", s: "Akihabara Radio Kaikan", t: "tokyo", p: 6600, mk: 22, vq: 1, v: ["Anya Forger", "Gojo Satoru", "Frieren", "Hatsune Miku"] },
  { id: "figuarts", n: "S.H.Figuarts Figure", d: "Bandai's articulated collector line.", c: "Collectibles", s: "Akihabara Radio Kaikan", t: "tokyo", p: 8250, mk: 22, vq: 1, v: ["Goku Ultra Instinct", "Kamen Rider"] },
  { id: "gachapon", n: "Gachapon Capsule Set (10 Random)", d: "We spin the weirdest gacha machines for you.", c: "Toys", s: "Gachapon Kaikan Akihabara", t: "tokyo", p: 3000, mk: 30 },
  { id: "kirby-plush", n: "Kirby Plush (Japan Only)", d: "Round pink perfection from Kirby Café.", c: "Toys", s: "Kirby Café Tokyo", t: "tokyo", p: 2860, vq: 1, v: ["Classic", "Sleeping", "Star Rod"] },

  // ================= LUXURY (PENDING — akan punya web terpisah) =================
  { id: "presage-var", skip: true, n: "Seiko Presage", d: "More JDM Presage references.", c: "Luxury", s: "Bic Camera Shinjuku", t: "tokyo", p: 48400, mk: 15, f: 80000, vq: 1, v: ["Sharp Edged GMT", "Style60s Blue", "Craftsmanship Arita"] },
  { id: "prospex", skip: true, n: "Seiko Prospex Diver", d: "Tool divers with JDM-only editions.", c: "Luxury", s: "Bic Camera Shinjuku", t: "tokyo", p: 60500, mk: 15, f: 80000, vq: 1, v: ["SPB143 62MAS", "King Turtle", "Alpinist Green"] },
  { id: "kingseiko", skip: true, n: "King Seiko SPB279", d: "The revived 1960s dress flagship.", c: "Luxury", s: "Seiko Boutique Ginza", t: "tokyo", p: 148500, mk: 15, f: 100000 },
  { id: "grandseiko", skip: true, n: "Grand Seiko", d: "Japan's finest watchmaking, domestic allocation.", c: "Luxury", s: "Grand Seiko Boutique Ginza", t: "tokyo", p: 748000, mk: 12, f: 150000, vq: 1, v: ["SBGA211 Snowflake", "SBGW231"] },
  { id: "citizen-var", skip: true, n: "Citizen JDM", d: "Citizen's Japan-only lines.", c: "Luxury", s: "Bic Camera Shinjuku", t: "tokyo", p: 41800, mk: 15, f: 80000, v: ["Tsuyosa Blue", "Attesa Titanium", "Series 8 830"] },
  { id: "oceanus", skip: true, n: "Casio Oceanus Manta", d: "Casio's secret luxury line, Japan only.", c: "Luxury", s: "Bic Camera Shinjuku", t: "tokyo", p: 198000, mk: 15, f: 100000 },
  { id: "gshock-metal", skip: true, n: "G-Shock Full Metal", d: "The grown-up G-Shocks.", c: "Luxury", s: "G-Shock Store Ginza", t: "tokyo", p: 71500, mk: 15, f: 80000, v: ["GMW-B5000D Silver", "GM-B2100D 'CasiOak'", "GMW-B5000GD Gold"] },
  { id: "porter-var", skip: true, n: "Porter Tanker Line", d: "More Tanker shapes from Yoshida & Co.", c: "Luxury", s: "Porter Ginza", t: "tokyo", p: 20900, mk: 20, vq: 1, v: ["Waist Bag", "2Way Briefcase", "Daypack", "Pouch S"] },
  { id: "porter-force", skip: true, n: "Porter Force Shoulder", d: "Military-spec nylon, quieter than Tanker.", c: "Luxury", s: "Porter Omotesando", t: "tokyo", p: 17600, mk: 20 },
  { id: "baobao-var", skip: true, n: "BAO BAO Issey Miyake", d: "More geometry from the Lucent line.", c: "Luxury", s: "Issey Miyake Ginza", t: "tokyo", p: 47300, mk: 15, f: 80000, vq: 1, v: ["Crossbody 6x6", "Tote 10x10", "Card Case"] },
  { id: "pleats-please", skip: true, n: "Pleats Please Issey Miyake", d: "The pleated pieces that pack flat and never crease.", c: "Luxury", s: "Issey Miyake Ginza", t: "tokyo", p: 30800, mk: 18, v: ["Basics Top", "Wide Pants", "Madame-T Scarf"] },
  { id: "vintage-lv", skip: true, n: "Vintage Louis Vuitton (Ginza Grade A)", d: "Curated vintage from Tokyo's famously honest resale shops.", c: "Luxury", s: "Komehyo Ginza", t: "tokyo", p: 180000, mk: 15, f: 120000, vq: 1, v: ["Speedy 30", "Pochette Accessoires", "Alma PM"] },
  { id: "vintage-gucci", skip: true, n: "Vintage Gucci (Tokyo Resale)", d: "Old-logo Gucci in Japan-grade condition.", c: "Luxury", s: "2nd Street Harajuku", t: "tokyo", p: 88000, mk: 15, f: 100000, v: ["Ophidia Pouch", "Horsebit Loafer"] },
  { id: "cdg-wallet-var", skip: true, n: "CDG Leather Wallet", d: "More CDG wallet colors and sizes.", c: "Luxury", s: "Dover Street Market Ginza", t: "tokyo", p: 19800, mk: 20, v: ["Zip Coin Red", "Bifold Black", "Long Wallet"] },
  { id: "gentlemonster-var", skip: true, n: "Gentle Monster", d: "More GM frames from the Seoul flagships.", c: "Luxury", s: "Gentle Monster Hongdae", t: "seoul", p: 280000, mk: 18, f: 70000, vq: 1, v: ["Lang Black", "My Ma Tortoise", "Bold Sunglasses"] },
  { id: "kaneko", skip: true, n: "Kaneko Optical Frame", d: "Sabae handmade eyewear, Japan's best-kept secret.", c: "Luxury", s: "Kaneko Gankyo Aoyama", t: "tokyo", p: 41800, mk: 18 },
  { id: "eyevan", skip: true, n: "Eyevan 7285 Frame", d: "Tokyo's poetic luxury eyewear.", c: "Luxury", s: "Eyevan Aoyama", t: "tokyo", p: 52800, mk: 18 },
  { id: "sailor-pen", skip: true, n: "Sailor Pro Gear Fountain Pen", d: "Hiroshima gold nibs with cult colorways.", c: "Luxury", s: "Itoya Ginza", t: "tokyo", p: 30800, mk: 18, v: ["Slim Black", "Ocean", "Yozakura"] },
  { id: "platinum-pen", skip: true, n: "Platinum #3776 Century", d: "The workhorse gold-nib pen of Japan.", c: "Luxury", s: "Itoya Ginza", t: "tokyo", p: 22000, mk: 18, v: ["Chartres Blue", "Bourgogne"] },
  { id: "hobonichi", skip: true, n: "Hobonichi Techo 2027", d: "The cult planner with Tomoe River paper.", c: "Luxury", s: "Itoya Ginza", t: "tokyo", p: 3080, mk: 25, v: ["A6 Book Only", "Cousin A5", "Weeks"] },
  { id: "4c-jewelry", skip: true, n: "4°C Silver Necklace", d: "Japan's gifting-standard jewelry brand.", c: "Luxury", s: "4°C Lumine Shinjuku", t: "tokyo", p: 16500, mk: 20 },
  { id: "ete", skip: true, n: "ete Layered Ring", d: "Delicate Tokyo jewelry, office-core.", c: "Luxury", s: "ete Lumine Shinjuku", t: "tokyo", p: 13200, mk: 20 },
  { id: "agete", skip: true, n: "agete Gold Earrings", d: "10k vintage-inspired pieces Japan queues for.", c: "Luxury", s: "agete Omotesando", t: "tokyo", p: 24200, mk: 20 },
  { id: "mikimoto", skip: true, n: "Mikimoto Pearl Pendant", d: "The original cultured pearl house, Ginza mothership.", c: "Luxury", s: "Mikimoto Ginza", t: "tokyo", p: 110000, mk: 15, f: 100000 },
  { id: "ganzo", skip: true, n: "Ganzo Cordovan Wallet", d: "Shell cordovan perfection, made in Tokyo.", c: "Luxury", s: "Ganzo Aoyama", t: "tokyo", p: 66000, mk: 18 },

  // ================= HOME & KITCHEN =================
  { id: "tojiro", n: "Tojiro DP Knife", d: "Tsubame-Sanjo steel, pro kitchens' budget favorite.", c: "Home & Kitchen", s: "Kappabashi Street", t: "tokyo", p: 9900, vq: 1, v: ["Gyuto 210mm", "Petty 150mm", "Nakiri"] },
  { id: "global-knife", n: "Global G-2 Chef Knife", d: "The all-steel Japanese classic since 1985.", c: "Home & Kitchen", s: "Kappabashi Street", t: "tokyo", p: 13200 },
  { id: "misono", n: "Misono UX10 Gyuto 210mm", d: "The Swedish-steel gyuto chefs whisper about.", c: "Home & Kitchen", s: "Kappabashi Street", t: "tokyo", p: 26400, mk: 18 },
  { id: "zojirushi-thermos", n: "Zojirushi Stainless Mug", d: "The vacuum mug that keeps coffee lava-hot.", c: "Home & Kitchen", s: "Bic Camera Shinjuku", t: "tokyo", p: 4180, vq: 1, v: ["360ml Black", "480ml Navy", "480ml Cream"] },
  { id: "zojirushi-pot", n: "Zojirushi Hot Water Dispenser 3L", d: "The push-button tea machine of Japanese homes.", c: "Home & Kitchen", s: "Bic Camera Shinjuku", t: "tokyo", p: 16500, f: 90000 },
  { id: "tiger-jug", n: "Tiger Vacuum Jug 1.2L", d: "Table thermos, showa-retro design revived.", c: "Home & Kitchen", s: "Bic Camera Shinjuku", t: "tokyo", p: 6600 },
  { id: "bento", n: "Japanese Bento Box", d: "Proper bento engineering for daily lunches.", c: "Home & Kitchen", s: "Tokyu Hands Shibuya", t: "tokyo", p: 3300, vq: 1, v: ["2-Tier Wappa Style", "Slim Stainless", "Kids Character"] },
  { id: "furoshiki", n: "Furoshiki Wrapping Cloth", d: "The reusable gift-wrap cloth, endless patterns.", c: "Home & Kitchen", s: "Musubi Kyoto", t: "tokyo", p: 2200, vq: 1, v: ["Wave Print 70cm", "Sakura 90cm"] },
  { id: "hasami", n: "Hasami Porcelain", d: "Stackable Nagasaki porcelain, design-award magnet.", c: "Home & Kitchen", s: "Nakagawa Masashichi", t: "tokyo", p: 2750, vq: 1, v: ["Mug Natural", "Plate Set", "Teapot Black"] },
  { id: "kutani", n: "Kutani Ware Pair Cups", d: "Five-color Ishikawa porcelain, gift-boxed.", c: "Home & Kitchen", s: "Takashimaya Nihombashi", t: "tokyo", p: 5500 },
  { id: "minoware", n: "Mino Ware Donburi Set", d: "Everyday Gifu ceramics with heirloom looks.", c: "Home & Kitchen", s: "Tokyu Hands Shibuya", t: "tokyo", p: 4400 },
  { id: "kinto", n: "Kinto", d: "Tokyo's minimalist tableware brand.", c: "Home & Kitchen", s: "Kinto Store Tokyo", t: "tokyo", p: 3080, vq: 1, v: ["Cast Glass Pair", "SCS Coffee Brewer", "Travel Tumbler"] },
  { id: "hario", n: "Hario V60 Starter Set", d: "The Tokyo-made pour-over standard.", c: "Home & Kitchen", s: "Tokyu Hands Shibuya", t: "tokyo", p: 4400, vq: 1, v: ["02 Ceramic White", "Metal Silver"] },
  { id: "kalita", n: "Kalita Wave Dripper 185", d: "Flat-bottom brewing, café-grade.", c: "Home & Kitchen", s: "Tokyu Hands Shibuya", t: "tokyo", p: 3850 },
  { id: "iwachu", n: "Iwachu Cast Iron Tetsubin", d: "Nambu ironware kettle, generations-lasting.", c: "Home & Kitchen", s: "Takashimaya Nihombashi", t: "tokyo", p: 16500, f: 90000, vq: 1, v: ["0.65L Black", "1.2L Arare"] },
  { id: "vermicular", n: "Vermicular Frying Pan 24cm", d: "Nagoya cast-iron pan with a devoted following.", c: "Home & Kitchen", s: "Vermicular Village", t: "tokyo", p: 19800, f: 90000 },
  { id: "muji-home", n: "MUJI Home Essentials", d: "The MUJI things people fly home with.", c: "Home & Kitchen", s: "MUJI Ginza", t: "tokyo", p: 4990, vq: 1, v: ["Aroma Diffuser", "Acrylic Storage Set", "Wall Clock"] },
  { id: "wakasa-chopsticks", n: "Wakasa Lacquer Chopsticks (Pair Gift)", d: "Mother-of-pearl lacquerware chopsticks, boxed.", c: "Home & Kitchen", s: "Takashimaya Nihombashi", t: "tokyo", p: 4400 },
  { id: "kamenoko", n: "Kamenoko Tawashi Brush", d: "The 100-year-old scrubbing turtle. Oddly perfect.", c: "Home & Kitchen", s: "Tokyu Hands Shibuya", t: "tokyo", p: 550, mk: 35 },
  { id: "marna", n: "Marna Kitchen Gadget Set", d: "Clever Japanese kitchen problem-solvers.", c: "Home & Kitchen", s: "Loft Shibuya", t: "tokyo", p: 2200, vq: 1, v: ["Butter Case & Knife", "Rice Measuring Set"] },
  { id: "imabari", n: "Imabari Towel Gift Set", d: "Ehime's certified cloud-soft towels.", c: "Home & Kitchen", s: "Imabari Honten Aoyama", t: "tokyo", p: 5500, vq: 1, v: ["Face Towel x2", "Bath Towel", "Gift Box Set"] },
  { id: "shoyeido", n: "Shoyeido Incense", d: "Kyoto incense house, est. 1705.", c: "Home & Kitchen", s: "Shoyeido Ginza", t: "tokyo", p: 1650, vq: 1, v: ["Nokiba Sticks", "Horin Coils", "Starter Set"] },
  { id: "hibi", n: "Hibi Match Incense", d: "Strike-anywhere incense matches from Kobe.", c: "Home & Kitchen", s: "Loft Shibuya", t: "tokyo", p: 990, vq: 1, v: ["Yuzu", "Sandalwood"] },
  { id: "kaico", n: "Kaico Enamel Kettle", d: "White enamel and maple — quiet Japanese design.", c: "Home & Kitchen", s: "Cotogoto Koenji", t: "tokyo", p: 13200, f: 90000 },
  { id: "donabe", n: "Iga Donabe Clay Pot", d: "The earthen pot for proper Japanese hotpot.", c: "Home & Kitchen", s: "Kappabashi Street", t: "tokyo", p: 8800, f: 90000, vq: 1, v: ["Size 8 (2-3 people)", "Size 9 (3-4 people)"] },
  { id: "oroshigane", n: "Copper Oroshigane Grater", d: "Hand-cut copper grater — wasabi's best friend.", c: "Home & Kitchen", s: "Kappabashi Street", t: "tokyo", p: 6600 },
];
